return {
  "folke/snacks.nvim",
  priority = 1000,
  lazy = false,
  opts = {
    bigfile = { enabled = true },
    explorer = { enabled = true },
    indent = { enabled = true },
    input = { enabled = true },
    notifier = {
      enabled = true,
      timeout = 3000,
    },
    picker = { enabled = true },
    quickfile = { enabled = true },
    scope = { enabled = true },
    scroll = { enabled = true },
    statuscolumn = { enabled = true },
    words = { enabled = true },
    styles = {
      notification = {
        -- wo = { wrap = true } -- Wrap notifications
      },
    },
  },
  -- stylua: ignore
  keys = {
    -- Top Pickers & Explorer
    { "<Leader><Space>", function() Snacks.picker.smart() end, desc = "Smart Find Files" },
    { "<Leader>,", function() Snacks.picker.buffers() end, desc = "Buffers" },
    { "<Leader>/", function() Snacks.picker.grep() end, desc = "Grep" },
    { "<Leader>:", function() Snacks.picker.command_history() end, desc = "Command History" },
    { "<Leader>n", function() Snacks.picker.notifications() end, desc = "Notification History" },
    { "<Leader>e", function() Snacks.explorer() end, desc = "File Explorer" },
    -- find
    { "<Leader>fb", function() Snacks.picker.buffers() end, desc = "Buffers" },
    { "<Leader>fc", function() Snacks.picker.files({ cwd = vim.fn.stdpath("config") }) end, desc = "Find Config File" },
    { "<Leader>ff", function() Snacks.picker.files() end, desc = "Find Files" },
    { "<Leader>fg", function() Snacks.picker.git_files() end, desc = "Find Git Files" },
    { "<Leader>fp", function() Snacks.picker.projects() end, desc = "Projects" },
    { "<Leader>fr", function() Snacks.picker.recent() end, desc = "Recent" },
    -- git
    { "<Leader>gb", function() Snacks.picker.git_branches() end, desc = "Git Branches" },
    { "<Leader>gl", function() Snacks.picker.git_log() end, desc = "Git Log" },
    { "<Leader>gL", function() Snacks.picker.git_log_line() end, desc = "Git Log Line" },
    { "<Leader>gs", function() Snacks.picker.git_status() end, desc = "Git Status" },
    { "<Leader>gS", function() Snacks.picker.git_stash() end, desc = "Git Stash" },
    { "<Leader>gd", function() Snacks.picker.git_diff() end, desc = "Git Diff (Hunks)" },
    { "<Leader>gf", function() Snacks.picker.git_log_file() end, desc = "Git Log File" },
    -- gh
    { "<Leader>gi", function() Snacks.picker.gh_issue() end, desc = "GitHub Issues (open)" },
    { "<Leader>gI", function() Snacks.picker.gh_issue({ state = "all" }) end, desc = "GitHub Issues (all)" },
    { "<Leader>gp", function() Snacks.picker.gh_pr() end, desc = "GitHub Pull Requests (open)" },
    { "<Leader>gP", function() Snacks.picker.gh_pr({ state = "all" }) end, desc = "GitHub Pull Requests (all)" },
    -- Grep
    { "<Leader>sb", function() Snacks.picker.lines() end, desc = "Buffer Lines" },
    { "<Leader>sB", function() Snacks.picker.grep_buffers() end, desc = "Grep Open Buffers" },
    { "<Leader>sg", function() Snacks.picker.grep() end, desc = "Grep" },
    { "<Leader>sw", function() Snacks.picker.grep_word() end, desc = "Visual selection or word", mode = { "n", "x" } },
    -- search
    { '<Leader>s"', function() Snacks.picker.registers() end, desc = "Registers" },
    { '<Leader>s/', function() Snacks.picker.search_history() end, desc = "Search History" },
    { "<Leader>sa", function() Snacks.picker.autocmds() end, desc = "Autocmds" },
    { "<Leader>sb", function() Snacks.picker.lines() end, desc = "Buffer Lines" },
    { "<Leader>sc", function() Snacks.picker.command_history() end, desc = "Command History" },
    { "<Leader>sC", function() Snacks.picker.commands() end, desc = "Commands" },
    { "<Leader>sd", function() Snacks.picker.diagnostics() end, desc = "Diagnostics" },
    { "<Leader>sD", function() Snacks.picker.diagnostics_buffer() end, desc = "Buffer Diagnostics" },
    { "<Leader>sh", function() Snacks.picker.help() end, desc = "Help Pages" },
    { "<Leader>sH", function() Snacks.picker.highlights() end, desc = "Highlights" },
    { "<Leader>si", function() Snacks.picker.icons() end, desc = "Icons" },
    { "<Leader>sj", function() Snacks.picker.jumps() end, desc = "Jumps" },
    { "<Leader>sk", function() Snacks.picker.keymaps() end, desc = "Keymaps" },
    { "<Leader>sl", function() Snacks.picker.loclist() end, desc = "Location List" },
    { "<Leader>sm", function() Snacks.picker.marks() end, desc = "Marks" },
    { "<Leader>sM", function() Snacks.picker.man() end, desc = "Man Pages" },
    { "<Leader>sp", function() Snacks.picker.lazy() end, desc = "Search for Plugin Spec" },
    { "<Leader>sq", function() Snacks.picker.qflist() end, desc = "Quickfix List" },
    { "<Leader>sR", function() Snacks.picker.resume() end, desc = "Resume" },
    { "<Leader>su", function() Snacks.picker.undo() end, desc = "Undo History" },
    { "<Leader>uC", function() Snacks.picker.colorschemes() end, desc = "Colorschemes" },
    -- LSP
    { "gd", function() Snacks.picker.lsp_definitions() end, desc = "Goto Definition" },
    { "gD", function() Snacks.picker.lsp_declarations() end, desc = "Goto Declaration" },
    { "gr", function() Snacks.picker.lsp_references() end, nowait = true, desc = "References" },
    { "gI", function() Snacks.picker.lsp_implementations() end, desc = "Goto Implementation" },
    { "gy", function() Snacks.picker.lsp_type_definitions() end, desc = "Goto T[y]pe Definition" },
    { "gai", function() Snacks.picker.lsp_incoming_calls() end, desc = "C[a]lls Incoming" },
    { "gao", function() Snacks.picker.lsp_outgoing_calls() end, desc = "C[a]lls Outgoing" },
    { "<Leader>ss", function() Snacks.picker.lsp_symbols() end, desc = "LSP Symbols" },
    { "<Leader>sS", function() Snacks.picker.lsp_workspace_symbols() end, desc = "LSP Workspace Symbols" },
  },
}
